AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/dummy/**/*
    - Rakefile
    - lib/tasks/**/*
  RunRailsCops: true

AbcSize:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  Exclude:
    - spec/**/*

DotPosition:
  Enabled: false

TrailingBlankLines:
  Enabled: false

HandleExceptions:
  Enabled: false

IfUnlessModifier:
  Enabled: false

LineLength:
  Exclude:
    - spec/**/*

MethodLength:
  Max: 15

PredicateName:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: false

WordArray:
  Enabled: false
